version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.23
    - 14.14.26
    - 14.14.29
    - 14.14.36
    - 15.0.0
  - dependency-name: typescript
    versions:
    - 3.9.9
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
    - 4.2.4
  - dependency-name: "@hydro-sdk/waveform"
    versions:
    - 0.0.1-nightly.23
    - 0.0.1-nightly.24
    - 0.0.1-nightly.25
    - 0.0.1-nightly.26
    - 0.0.1-nightly.27
    - 0.0.1-nightly.28
    - 0.0.1-nightly.29
    - 0.0.1-nightly.30
    - 0.0.1-nightly.31
    - 0.0.1-nightly.32
    - 0.0.1-nightly.33
    - 0.0.1-nightly.34
    - 0.0.1-nightly.35
  - dependency-name: typescript-to-lua
    versions:
    - 0.37.1
    - 0.38.0
    - 0.38.1
    - 0.39.0
    - 0.39.1
    - 0.39.2
  - dependency-name: typedoc-neo-theme
    versions:
    - 1.1.0
