description: A new Flutter project.
name: hydro_sdk
version: 1.0.0+1
dependencies: 
  analyzer: ^1.7.1
  args: ^2.1.1
  benchmark_harness: ^2.0.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  http: ^0.13.3
  json_serializable: ^4.1.3
  petitparser: 4.1.0
  recase: ^4.0.0
  tuple: ^2.0.0
  flutter: 
    sdk: flutter
  archive: ^3.1.2
  cli_util: ^0.3.0
  code_builder: ^4.0.0
  corsac_jwt: ^1.0.0-nullsafety.1
  dart_console: ^1.0.0
  dart_style: ^2.0.1
  encrypt: ^5.0.0
  filesize: ^2.0.1
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  pointycastle: ^3.1.1
  rsa_pkcs: ^2.0.0
  synchronized: ^3.0.0
  uuid: ^3.0.4
  watcher: ^1.0.0
  glob: 2.0.1
  path_provider: null
  quiver: 3.0.1
dev_dependencies: 
  import_sorter: null
  build_runner: null
  test: ^1.16.5
  waveform: ^0.0.1-nightly.48
  flutter_test:
    sdk: flutter
environment: 
  sdk: '>=2.12.0 <3.0.0'
flutter: 
  uses-material-design: true
